### ISSUE TITLE
question

### ISSUE THREAD

**Issue by HeadReaper-hc** [manhha1402/3D-Reconstruction-using-Dense-Optical-Flow#1]
Hi,
    Do you get the result picture "OpticalFlow.png"  by "im0.png" and "im1.png"?

**Comment by manhha1402** [comment]
Hi, 
I think so. Sorry, the code has been implemented for 4 years, so I don't remember in detail

**Comment by HeadReaper-hc** [comment]
Got it. Thank you for your reply.
